### ISSUE TITLE
confusion on `HttpsConnetor::wrap_connector`

### ISSUE THREAD

**Issue by niklasad1** [rustls/hyper-rustls#169] opened 2022-04-30 07:31 UTC
Hey,

I thought the following would work to make `https or http` calls:
```rust

let mut connector = HttpConnector::new();
let connector = hyper_rustls::HttpsConnectorBuilder::new()
   .with_native_roots()
   .https_or_http()
   .enable_http1()
   .wrap_connector(connector),
		
let client = Client::builder().build::<_, hyper::Body>(connector);
```

but hyper reports back that `https` is not valid.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Transport(HTTP error: error trying to connect: invalid URL, scheme is not http)'

**Comment by niklasad1** [comment] 2022-04-30 07:44
Ah I see the entire connector config is used then I guess

**Comment by djc** [comment] 2022-05-10 08:47
I'm not sure what the issue is here, or if there was an issue in hyper-rustls at all. Is this actionable for us?

**Comment by cpu** [comment] 2023-03-31 17:15
Since the original poster hasn't replied with more detail I'm going to close this issue as unactionable for the time being. Thanks.

**Closed by cpu** 2023-03-31 17:15 UTC

**Comment by niklasad1** [comment] 2023-12-11 09:27
Hey again.

Sorry forgot to answer and the issue was that the `HttpConnector` enforces the URI to be http and https is denied by default. Thus, the following fixes the panic:

```
let mut connector = HttpConnector::new();
connectors.enforce_http(false);
let connector = hyper_rustls::HttpsConnectorBuilder::new()
   .with_native_roots()
   .https_or_http()
   .enable_http1()
   .wrap_connector(connector),
		
let client = Client::builder().build::<_, hyper::Body>(connector);
```
